name: ViaRewind-Legacy-Support-MercurioMC
version: ${version}
main: com.viaversion.viarewind.legacysupport.BukkitPlugin
api-version: 1.13

authors: [Gerrygames]
website: https://github.com/ViaVersion/ViaRewind-Legacy-Support

depend: [ViaVersion]
